spring.application.name=logging-middleware


logging.api.base-url=http://4.224.186.213/evaluation-service

logging.api.client-id=ff34321d-d2b8-4916-a068-54a052e09504
logging.api.client-secret=FhKehmjenCCGBufq

logging.api.email=sanjaisp7@gmail.com
logging.api.name=sanjay m
logging.api.roll-no=23aib23
logging.api.access-code=WjNyCT